import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
// import "./globals.css";
import TanStackProvider from "../components/TanStackProvider/TanStackProvider";

export const metadata: Metadata = {
  title: "notehub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal:  React.ReactNode
}>) {
  return (
    <html lang="en">
      <body style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}>
        <TanStackProvider>
          <Header />
          <hr />
          {children}
          {modal}
          <hr />
          <Footer />
        </TanStackProvider>

      </body>
    </html>
  );
}

